# Omise Configuration
omise.public-key=pkey_test_61thxp7bhe4onhg2b3d
omise.secret-key=skey_test_61thxp7udl0ndph48i7

# Server Configuration
server.port=8081


spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
spring.web.resources.cache.period=0