# Omise Configuration
omise.public-key=pkey_test_61thxp7bhe4onhg2b3d
omise.secret-key=skey_test_61thxp7udl0ndph48i7

# Line Configuration
line.channel-secret=1046e4804a4e8dbfdf8b2c4ff4ce867f
line.access-token=qK0cQX53mfy3cLL3juoJ3sDEu2afLoozw8QeVPS/0bIJh8SFYr9GaCdxfJAfEjaXDreuQuN+InDJnv4nxZIrkLC0dIDttvPIt/Xgqix4LF2etHVwjd0AjCHDuTnQtxOymodMsFG5JmItS2tum0pSnwdB04t89/1O/w1cDnyilFU=
line.liff-id=2007933712-ZQRPnn2o

# Server Configuration
server.port=8081


spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
spring.web.resources.cache.period=0